### ISSUE TITLE
Annoying Update Killed API

### ISSUE THREAD

**Issue by Hacker1254** [PlagueVRC/PlagueButtonAPI#2]
Ex
![image](https://user-images.githubusercontent.com/69991448/155650690-904e58d7-8b06-4dde-a18f-5bda771ed386.png)

**Comment by MistressPlague** [comment]
Are you not just missing correct reference files?

**Comment by Hacker1254** [comment]
No when using older ver of the UI ele it works, but not in vrc
i think VRC changed an name thingie

**Comment by MistressPlague** [comment]
It's the same for me on latest ref files.
I'll look into it further, though.

**Comment by Hacker1254** [comment]
Alr, Take ur time

**Comment by MistressPlague** [comment]
Updated. Await automated builds.
