### ISSUE TITLE
Toggle States Reseting After QM Menu Open

### ISSUE THREAD

**Issue by Hacker1254** [PlagueVRC/PlagueButtonAPI#3]
Like as the title states, toggles resets when opening QM menu

**Comment by MistressPlague** [comment]
No instructions to recreate?

**Comment by Hacker1254** [comment]
for me, any normal toggle will reset when opening the QM menu

**Comment by Hacker1254** [comment]
so, if i had a Avatar log on, and i open the QM Menu, it gets switched Off

**Comment by MistressPlague** [comment]
Fixed?
